vich_uploader:
    db_driver: orm
    

    mappings:
        products:
            
            uri_prefix:         '%products%'
            upload_destination: '%kernel.project_dir%/public%products%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false